### ISSUE TITLE
[JS-SDK] NFT minting is failing

### ISSUE THREAD

**Issue by behumble** [ryukato/developers-sdk#26]
I realized that the code below is not working:
```javascript
httpClient.mintNonFungibleToken(contractId, tokenType, new NonFungibleTokenRequest(
        ownerAddress,
        ownerSecret,
        name: 'NFT',
        meta,
        null,
        toUserId))
```

it'll give us `toAddress` field with `null` which means both `toAddress` and `toUserId` will be passed to a request body and signature target.

instead, I was able to workaround this by NOT using the constructor. would you let me know if there's better way?
```javascript
httpClient.mintNonFungibleToken(contractId, tokenType, {
        ownerAddress,
        ownerSecret,
        name: 'NFT',
        meta,
        toUserId
})
```

**Comment by ryukato** [comment]
This has been resolved by release of v1.0.0
