### ISSUE TITLE
[JS] export SignatureGenerator

### ISSUE THREAD

**Issue by behumble** [ryukato/developers-sdk#27]
I hope I can use `SignatureGenerator` to make requests which are undocumented.
is there any way to use `SignatureGenerator`?
I had to duplicate signature generation logic.

**Comment by ryukato** [comment]
I think we can do that by following codes to `index.ts`.
`export * from './lib/http-client-base';`

I still wondering why you have duplicated signature generation logic? 
I think you don't need to worry about signature generation if you use `HttpClient` from sdk for javascript. 
@behumble is there anything I missed?

**Comment by behumble** [comment]
thank you for the response @ryukato 
I thought as a NPM package user, I can not use non-exported class (`SignatureGenerator`)
and I had to call ELN API which is not implemented in `HttpClient` and I couldn't use `SignatureGenerator` because it's not exported.
could you let me know if there's a more easy & elegant way to achieve this?

**Comment by ryukato** [comment]
This has been fixed and please see the fix on [new repository](https://github.com/ryukato/developers-sdk-js)
